#!/bin/sh
doSed "s!<show_legend>true</show_legend>!<show_legend>false</show_legend>!" $1
doSed "s!<show_toolbar>true</show_toolbar>!<show_toolbar>false</show_toolbar>!" $1
doSed "s!<show_plot_area_border>false</show_plot_area_border>!<show_plot_area_border>true</show_plot_area_border>!" $1
