TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

INC_cygwin32 += wpcap.h wpcap-bpf.h

LIB_INSTALLS_cygwin32 += ../Libnet.lib
LIB_INSTALLS_cygwin32 += ../libwpcap.a
BIN_INSTALLS_cygwin32 += ../Libnet.dll

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
